[tool.ruff]
target-version = "py39"
line-length = 120
# Add micropython-specific (and viper-specific) built-in names
builtins = ["const", "micropython", "ptr", "ptr8", "ptr16", "ptr32"]

[tool.ruff.lint]
# Select all stable linting rules.
select = ["ALL"]
ignore = [
    "TRY",
    "EM",
    "Q000",
]

[tool.ruff.lint.isort]
# Use 2 lines after imports
lines-after-imports = 2

[tool.ruff.lint.flake8-annotations]
suppress-none-returning = true
